Ext4.define("LABKEY.study.panel.PublicationDetails", {
    extend: "Ext.Container",

    tpl: new Ext4.XTemplate(
        '<div id="labkey-publication-details-content">',
        '   <tpl if="studies">',
        '       <div>',
        '       <span class="labkey-publication-detail-label">studies:</span>',
        '       <tpl for="studies">',
        '           <tpl if="url">',
        '               <span class="labkey-study-short-name"><a href="{url:htmlEncode}">{shortName:htmlEncode}</a></span>',
        '           <tpl else>',
        '               <span class="labkey-study-short-name">{shortName:htmlEncode}</span>',
        '           </tpl>',
        '       </tpl>',
        '       </div>',
        '   </tpl>',
        '   <div class="labkey-publication-identifiers">',
        '   <tpl if="pmid">',
        '       <span class="labkey-publication-identifier">PMID: <a href="http://www.ncbi.nlm.nih.gov/pubmed/?term={pmid:htmlEncode}" class="labkey-text-link" target="_blank">{pmid:htmlEncode}</a></span>',
        '   </tpl>',
        '   <tpl if="pmcid">',
        '       <span class="labkey-publication-identifier">PMCID: <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/{pmcid:htmlEncode}" class="labkey-text-link" target="_blank">{pmcid:htmlEncode}</a></span>',
        '   </tpl>',
        '   <tpl if="doi">',
        '       <span class="labkey-publication-identifier">DOI: <a href="http://dx.doi.org/{doi:htmlEncode}" class="labkey-text-link" target="_blank">{doi:htmlEncode}</a></span>',
        '   </tpl>',
        '   </div>',
        '   <tpl if="urls"/>',
        '       <div class="labkey-publication-links">',
        '       <tpl for="urls">',
        '       <tpl if="link && linkText">',
        '           <a class="labkey-text-link" href="{link:htmlEncode}" target="_blank">{linkText:htmlEncode}</a>',
        '           <br/>',
        '           </tpl>',
        '       </tpl>',
        '       </div>',
        '   </tpl>',
        '   <tpl if="dataUrl">',
        '       <a class="labkey-text-link" href="{dataUrl:htmlEncode}" target="_blank">Clinical and Assay Data</a>',
        '   </tpl>',
        '   <tpl if="keywords">',
            '       <div class="labkey-publication-keywords">',
            '           <div class="labkey-publication-detail-label">keywords</div>',
            '           {keywords:htmlEncode}',
            '       <div>',
            '   </tpl>',
        '   <tpl if="abstractText">',
        '       <div class="labkey-publication-abstract">',
        '           <div class="labkey-publication-detail-label">abstract</div>',
        '           {abstractText:htmlEncode}',
        '       <div>',
        '   </tpl>',
        '   <tpl if="thumbnails">',
        '   <ul class="labkey-figures-list">',
        '   <tpl for="thumbnails">',
        '       <li class="labkey-figure"><a href="{link}" target="_blank"><img src="{linkText}"></a>',
        '   </tpl>',
        '   </ul>',
        '   </tpl>',
        '</div>'
    )

});