Ext4.define("LABKEY.study.panel.PublicationDetails", {
    extend: "Ext.Container",

    tpl: new Ext4.XTemplate(
        '<div id="labkey-publication-details-content">',
        '   <tpl if="urls"/>',
        '       <div class="labkey-publication-links">',
        '       <tpl for="urls">',
        '       <tpl if="link && linkText">',
        '           <div><a class="labkey-text-link" href="{link:htmlEncode}" target="_blank">{linkText:htmlEncode}</a></div>',
        '           </tpl>',
        '       </tpl>',
        '       </div>',
        '   </tpl>',

        '   <div class="labkey-publication-identifiers">',
        '   <tpl if="pmid">',
        '       <span class="labkey-publication-identifier"><a href="http://www.ncbi.nlm.nih.gov/pubmed/?term={pmid:htmlEncode}" class="labkey-text-link" target="_blank">PMID {pmid:htmlEncode}</a></span>',
        '   </tpl>',
        '   <tpl if="pmcid">',
        '       <span class="labkey-publication-identifier"><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/{pmcid:htmlEncode}" class="labkey-text-link" target="_blank">PMCID {pmcid:htmlEncode}</a></span>',
        '   </tpl>',
        '   <tpl if="doi">',
        '       <span class="labkey-publication-identifier"><a href="http://dx.doi.org/{doi:htmlEncode}" class="labkey-text-link" target="_blank">DOI {doi:htmlEncode}</a></span>',
        '   </tpl>',
        '   </div>',
        '   <tpl if="studies">',
        '       <div class="labkey-publication-studies">',
        '       <span class="labkey-publication-detail-label">Studies</span>',
        '       <tpl for="studies">',
        '           <tpl if="url">',
        '               <span class="labkey-study-short-name"><a href="{url:htmlEncode}">{shortName:htmlEncode}</a></span>',
        '           <tpl else>',
        '               <span class="labkey-study-short-name">{shortName:htmlEncode}</span>',
        '           </tpl>',
        '       </tpl>',
        '       </div>',
        '   </tpl>',
        '   <tpl if="keywords">',
        '       <div class="labkey-publication-keywords">',
        '           <span class="labkey-publication-detail-label">Keywords</span>',
        '           {keywords:htmlEncode}',
        '       <div>',
        '   </tpl>',
        '   <tpl if="abstractText">',
        '       <div class="labkey-publication-abstract">',
        '           <span class="labkey-publication-detail-label">Abstract</span>',
        '           {abstractText:htmlEncode}',
        '       </div>',
        '   </tpl>',
        '   <tpl if="dataUrl">',
        '       <a class="labkey-text-link labkey-publication-data-link" href="{dataUrl:htmlEncode}" target="_blank">Clinical and Assay Data</a>',
        '   </tpl>',
        '   <tpl if="thumbnails">',
        '   <ul class="labkey-figures-list">',
        '   <tpl for="thumbnails">',
        '       <li class="labkey-figure"><a href="{link}" target="_blank"><img src="{linkText}"></a>',
        '   </tpl>',
        '   </ul>',
        '   </tpl>',
        '</div>'
    )

});